//! W12 runner boundary tests (TEST_MATRIX T49–T52) — every job runs the
//! REAL `void-fake-worker` binary (workers/fake), built from this test's
//! setup. Artifacts are genuine synth output: a fresh sine WAV per spec.

use std::fs;
use std::path::{Path, PathBuf};

use std::time::Duration;
use void_assets::AssetStore;
use void_jobs::{
    decide, Admit, JobBudget, JobDb, JobKind, JobRunner, JobSpec, JobStatus, Reservations,
    RunContext, RunOutcome, WorkerRuntime,
};

fn worker_exe() -> PathBuf {
    // Build the real fixture binary once per test-process run; a
    // missing or stale binary fails loudly rather than passing mocked.
    //
    // `cargo build` re-emits the destination binary (unlink+hardlink)
    // even on a fresh check — observed on macOS as intermittent
    // ENOENT/“binary missing” when 13 parallel tests each invoked the
    // same build. `OnceLock` serializes it so every spawn happens after
    // the single replacement completes.
    static EXE: std::sync::OnceLock<PathBuf> = std::sync::OnceLock::new();
    EXE.get_or_init(|| {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
        let manifest = root.join("workers/fake/Cargo.toml");
        let status = std::process::Command::new(env!("CARGO"))
            .args(["build", "--manifest-path"])
            .arg(&manifest)
            .status()
            .expect("cargo build fake worker");
        assert!(status.success(), "fake worker build failed");
        let exe = root.join("workers/fake/target/debug/void-fake-worker");
        assert!(exe.is_file(), "fake worker binary missing at {exe:?}");
        exe
    })
    .clone()
}

fn spec(params: serde_json::Value) -> JobSpec {
    JobSpec {
        job_id: uuid::Uuid::new_v4().to_string(),
        project_id: uuid::Uuid::new_v4().to_string(),
        source_revision: "7".into(),
        context_sha256: "ab".repeat(32),
        kind: JobKind::Symbolic,
        runtime_id: "void-fake-worker".into(),
        runtime_sha256: "cd".repeat(32),
        model_id: Some("fake-synth".into()),
        model_sha256: Some("ef".repeat(32)),
        inputs: vec!["11".repeat(32)],
        parameters: params,
        reservations: Reservations {
            ram_bytes: (64 * 1024 * 1024u64).to_string(),
            vram_bytes: "0".into(),
            cpu_threads: 1,
        },
        deadline_monotonic_ns: "0".into(),
        output_scope_token: "test-scope".into(),
        cloud_consent_id: None,
    }
}

struct Fixture {
    root: tempfile::TempDir,
    db: JobDb,
    store: AssetStore,
    runtime: WorkerRuntime,
}

fn fixture() -> Fixture {
    let root = tempfile::tempdir().unwrap();
    let db = JobDb::open(root.path().join("index.db")).unwrap();
    let store = AssetStore::new(root.path().join("assets"), 64 * 1024 * 1024).unwrap();
    let runtime = WorkerRuntime::new(worker_exe());
    Fixture {
        root,
        db,
        store,
        runtime,
    }
}

fn runner(f: &Fixture) -> JobRunner {
    // JobRunner takes the db by value — open a second connection over
    // the same file (schema owner remains the first).
    let db = JobDb::open(f.root.path().join("index.db")).unwrap();
    JobRunner::new(db, f.store.clone(), f.root.path().to_path_buf())
}

fn budget(cpu_seconds: u64, memory_bytes: u64, wall_ns: u64) -> JobBudget {
    JobBudget {
        cpu_seconds,
        memory_bytes,
        vram_bytes: 0,
        deadline_monotonic_ns: 0,
        wall_ns,
    }
}

fn ctx<'a>(runtime: &'a WorkerRuntime, b: JobBudget) -> RunContext<'a> {
    RunContext {
        runtime,
        budget: b,
        model_version: Some("1.0.0".into()),
    }
}

fn generous() -> JobBudget {
    budget(60, 256 * 1024 * 1024, 30_000_000_000)
}

fn wav_sha(path: &Path) -> String {
    let b = fs::read(path).unwrap();
    use sha2::{Digest, Sha256};
    let mut h = Sha256::new();
    h.update(&b);
    h.finalize().iter().map(|x| format!("{x:02x}")).collect()
}

#[test]
fn t49_happy_path_real_sine_wav_and_provenance() {
    let f = fixture();
    let r = runner(&f);
    let s = spec(serde_json::json!({"mode":"succeed","durationMs":50,"freqHz":330,"seed":7}));
    f.db.submit(&s).unwrap();
    let jid = s.job_id.clone();
    let out = r.run(&s, &ctx(&f.runtime, generous())).unwrap();
    let RunOutcome::Succeeded {
        artifacts,
        stray_files,
        ..
    } = out
    else {
        panic!("expected success: {out:?}")
    };
    assert_eq!(stray_files, 0);
    assert_eq!(artifacts.len(), 1);
    // Real generated bytes: the WAV in the store hashes to the
    // provenance-recorded sha and starts with RIFF.
    let abs = &artifacts[0].asset_abs;
    assert!(abs.is_file());
    assert_eq!(&fs::read(abs).unwrap()[..4], b"RIFF");
    assert_eq!(artifacts[0].sha256, wav_sha(abs));
    assert_eq!(f.db.get(&jid).unwrap().status, JobStatus::Succeeded);
    // provenance.json + result.json published beside the asset refs.
    let dir = f.root.path().join("jobs").join(&jid);
    let prov: serde_json::Value =
        serde_json::from_slice(&fs::read(dir.join("provenance.json")).unwrap()).unwrap();
    assert_eq!(prov["jobId"], jid);
    assert_eq!(prov["modelId"], "fake-synth");
    assert_eq!(prov["modelVersion"], "1.0.0");
    assert_eq!(prov["sourceRevision"], "7");
    assert_eq!(prov["artifacts"][0]["sha256"], artifacts[0].sha256);
    assert_eq!(prov["parameters"]["freqHz"], 330);
    assert!(prov["runtime"]["argvSha256"].as_str().unwrap().len() == 64);
    assert_eq!(prov["runtime"]["executable"], "void-fake-worker");
    assert_eq!(prov["inputs"][0], "11".repeat(32));
    let card: serde_json::Value =
        serde_json::from_slice(&fs::read(dir.join("result.json")).unwrap()).unwrap();
    assert_eq!(card["status"], "succeeded");
}

#[test]
fn t49_dedup_same_params_same_artifact_hash() {
    let f = fixture();
    let r = runner(&f);
    let params = serde_json::json!({"mode":"succeed","durationMs":30,"freqHz":220,"seed":3});
    let s1 = spec(params.clone());
    let s2 = spec(params);
    f.db.submit(&s1).unwrap();
    f.db.submit(&s2).unwrap();
    let a1 = match r.run(&s1, &ctx(&f.runtime, generous())).unwrap() {
        RunOutcome::Succeeded { artifacts, .. } => artifacts[0].sha256.clone(),
        o => panic!("{o:?}"),
    };
    let a2 = match r.run(&s2, &ctx(&f.runtime, generous())).unwrap() {
        RunOutcome::Succeeded { artifacts, .. } => artifacts[0].sha256.clone(),
        o => panic!("{o:?}"),
    };
    assert_eq!(a1, a2, "deterministic synth → same sha → store dedups");
}

#[test]
fn t49_worker_reported_failure_is_failed_not_succeeded() {
    let f = fixture();
    let r = runner(&f);
    let s = spec(serde_json::json!({"mode":"fail"}));
    f.db.submit(&s).unwrap();
    let jid = s.job_id.clone();
    match r.run(&s, &ctx(&f.runtime, generous())).unwrap() {
        RunOutcome::Failed { error, .. } => assert!(error.contains("requested failure")),
        o => panic!("{o:?}"),
    }
    let rec = f.db.get(&jid).unwrap();
    assert_eq!(rec.status, JobStatus::Failed);
    assert!(rec.result.unwrap()["error"]
        .as_str()
        .unwrap()
        .contains("requested failure"));
}

#[test]
fn t49_crash_without_result_line_fails() {
    let f = fixture();
    let r = runner(&f);
    let s = spec(serde_json::json!({"mode":"crash"}));
    f.db.submit(&s).unwrap();
    match r.run(&s, &ctx(&f.runtime, generous())).unwrap() {
        RunOutcome::Failed {
            error, exit_code, ..
        } => {
            assert_eq!(exit_code, Some(3));
            assert!(error.contains("without a result line"), "{error}");
        }
        o => panic!("{o:?}"),
    }
}

#[test]
fn t51_staging_escape_is_rejected() {
    let f = fixture();
    let r = runner(&f);
    let s = spec(serde_json::json!({"mode":"escape"}));
    f.db.submit(&s).unwrap();
    match r.run(&s, &ctx(&f.runtime, generous())).unwrap() {
        RunOutcome::Failed { error, .. } => assert!(error.contains("staging"), "{error}"),
        o => panic!("{o:?}"),
    }
    // Nothing published, nothing imported.
    assert!(
        !f.root.path().join("jobs").exists()
            || fs::read_dir(f.root.path().join("jobs")).unwrap().count() == 0
    );
}

#[test]
fn t49_cancel_queued_job_directly() {
    let f = fixture();
    let r = runner(&f);
    let s = spec(serde_json::json!({"mode":"succeed"}));
    f.db.submit(&s).unwrap();
    assert_eq!(r.request_cancel(&s.job_id).unwrap(), JobStatus::Cancelled);
    assert_eq!(f.db.get(&s.job_id).unwrap().status, JobStatus::Cancelled);
}

#[test]
fn t49_cancel_running_kill_and_late_result_quarantined() {
    let f = fixture();
    let r = runner(&f);
    let token = r.cancel_token();
    let s = spec(serde_json::json!({"mode":"sleep","durationMs":100}));
    f.db.submit(&s).unwrap();
    let jid = s.job_id.clone();
    let s_run = s.clone();
    // Runner moves into the worker thread (JobDb conn is !Sync); the
    // test cancels via the token + a second connection — exactly how a
    // CancelJob op would reach it.
    let handle = std::thread::spawn(move || {
        let c = ctx_static();
        r.run(&s_run, &c)
    });
    std::thread::sleep(Duration::from_millis(200));
    let db2 = JobDb::open(f.root.path().join("index.db")).unwrap();
    db2.cancel(&jid).unwrap(); // running → cancelling
    token.cancel(); // runner-side cooperative cancel
    let out = handle.join().unwrap().unwrap();
    assert!(matches!(out, RunOutcome::Cancelled { .. }), "{out:?}");
    let rec = f.db.get(&jid).unwrap();
    assert_eq!(rec.status, JobStatus::Cancelled);
    // No provenance/result publish; staging torn down.
    assert!(!f
        .root
        .path()
        .join("jobs")
        .join(&jid)
        .join("provenance.json")
        .exists());
    assert!(!f
        .root
        .path()
        .join("staging")
        .join(format!("job-{jid}"))
        .exists());
}

fn ctx_static() -> RunContext<'static> {
    // Tests spawn against the module-level built binary — the path is
    // leaked once, keeping the borrow static for the worker thread.
    static RUNTIME: std::sync::OnceLock<WorkerRuntime> = std::sync::OnceLock::new();
    RunContext {
        runtime: RUNTIME.get_or_init(|| WorkerRuntime::new(worker_exe())),
        budget: generous(),
        model_version: Some("1.0.0".into()),
    }
}

#[test]
fn t50_deadline_kills_sleeping_worker() {
    let f = fixture();
    let r = runner(&f);
    // Worker naps 30s; wall budget 200ms must kill it fast.
    let s = spec(serde_json::json!({"mode":"sleep","durationMs":100}));
    f.db.submit(&s).unwrap();
    let b = budget(60, 256 * 1024 * 1024, 200_000_000);
    let started = std::time::Instant::now();
    let out = r.run(&s, &ctx(&f.runtime, b)).unwrap();
    assert!(
        started.elapsed() < Duration::from_secs(10),
        "deadline must fire promptly"
    );
    match out {
        RunOutcome::Failed { error, .. } => assert!(error.contains("deadline"), "{error}"),
        o => panic!("{o:?}"),
    }
}

#[test]
fn t50_memory_budget_kills_greedy_worker() {
    let f = fixture();
    let r = runner(&f);
    let s = spec(serde_json::json!({"mode":"oom","durationMs":100}));
    f.db.submit(&s).unwrap();
    // 128MiB address space — the oom fixture allocates 64MiB chunks.
    let b = budget(60, 128 * 1024 * 1024, 20_000_000_000);
    let out = r.run(&s, &ctx(&f.runtime, b)).unwrap();
    match out {
        RunOutcome::Failed { error, .. } => {
            assert!(!error.is_empty());
        }
        o => panic!("expected failure under memory budget: {o:?}"),
    }
}

#[test]
fn t50_cpu_budget_kills_spinner() {
    let f = fixture();
    let r = runner(&f);
    let s = spec(serde_json::json!({"mode":"spin"}));
    f.db.submit(&s).unwrap();
    let b = budget(1, 256 * 1024 * 1024, 20_000_000_000);
    let started = std::time::Instant::now();
    let out = r.run(&s, &ctx(&f.runtime, b)).unwrap();
    assert!(started.elapsed() < Duration::from_secs(15));
    match out {
        RunOutcome::Failed { error, .. } => assert!(!error.is_empty()),
        o => panic!("expected CPU-cap failure: {o:?}"),
    }
}

#[test]
fn t50_admission_four_waiting_one_heavy_two_small() {
    let f = fixture();
    let light = serde_json::json!({"mode":"succeed"});
    let mk = |ram: &str, vram: &str, threads: u32| {
        let mut s = spec(light.clone());
        s.reservations = Reservations {
            ram_bytes: ram.into(),
            vram_bytes: vram.into(),
            cpu_threads: threads,
        };
        s
    };
    // Two small running + one heavy running → both slots taken.
    let small1 = mk("67108864", "0", 1);
    let small2 = mk("67108864", "0", 1);
    let heavy = mk("34359738368", "0", 8);
    for s in [&small1, &small2, &heavy] {
        f.db.submit(s).unwrap();
        f.db.start(&s.job_id).unwrap();
    }
    // A third small job: running slots exhausted → Queue.
    assert_eq!(
        decide(&f.db, &mk("67108864", "0", 1)).unwrap(),
        Admit::Queue
    );
    // A second heavy: heavy slot taken → Queue.
    assert_eq!(
        decide(&f.db, &mk("34359738368", "0", 8)).unwrap(),
        Admit::Queue
    );
    // Fill the waiting room: 4 queued.
    for _ in 0..4 {
        let s = mk("67108864", "0", 1);
        f.db.submit(&s).unwrap();
    }
    // Fifth waiter is refused.
    match decide(&f.db, &mk("67108864", "0", 1)) {
        Err(e) => assert!(e.to_string().contains("full"), "{e}"),
        a => panic!("expected Busy, got {a:?}"),
    }
    // Fresh db: no contention → StartNow.
    let f2 = fixture();
    assert_eq!(
        decide(&f2.db, &mk("67108864", "0", 1)).unwrap(),
        Admit::StartNow
    );
}

#[test]
fn t49_stray_files_counted_not_committed() {
    let f = fixture();
    let r = runner(&f);
    let s = spec(serde_json::json!({"mode":"stray","durationMs":20}));
    f.db.submit(&s).unwrap();
    let out = r.run(&s, &ctx(&f.runtime, generous())).unwrap();
    match out {
        RunOutcome::Succeeded {
            artifacts,
            stray_files,
            ..
        } => {
            assert_eq!(artifacts.len(), 1);
            assert_eq!(stray_files, 1, "stray.bin counted, never imported");
        }
        o => panic!("{o:?}"),
    }
    let prov: serde_json::Value = serde_json::from_slice(
        &fs::read(
            f.root
                .path()
                .join("jobs")
                .join(&s.job_id)
                .join("provenance.json"),
        )
        .unwrap(),
    )
    .unwrap();
    assert_eq!(prov["measured"]["strayFiles"], 1);
    // Store contains exactly the declared artifact.
    let mut count = 0;
    for e in fs::read_dir(f.root.path().join("assets/sha256")).unwrap() {
        e.unwrap();
        count += 1;
    }
    assert_eq!(count, 1);
}

#[test]
fn t49_rerun_terminal_job_rejected() {
    let f = fixture();
    let r = runner(&f);
    let s = spec(serde_json::json!({"mode":"succeed","durationMs":20}));
    f.db.submit(&s).unwrap();
    r.run(&s, &ctx(&f.runtime, generous())).unwrap();
    // Exactly one terminal outcome — a second run() is an error.
    match r.run(&s, &ctx(&f.runtime, generous())) {
        Err(e) => assert!(e.to_string().contains("transition"), "{e}"),
        Ok(o) => panic!("re-run of terminal job must fail: {o:?}"),
    }
}
