# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AddTrackOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AddTrackOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAddTrackOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AddTrackOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AddTrackOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AddTrackOp
    def Kind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # AddTrackOp
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AddTrackOp
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

def AddTrackOpStart(builder):
    builder.StartObject(4)

def Start(builder):
    AddTrackOpStart(builder)

def AddTrackOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    AddTrackOpAddTrackId(builder, trackId)

def AddTrackOpAddKind(builder, kind):
    builder.PrependInt8Slot(1, kind, 0)

def AddKind(builder, kind):
    AddTrackOpAddKind(builder, kind)

def AddTrackOpAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    AddTrackOpAddName(builder, name)

def AddTrackOpAddIndex(builder, index):
    builder.PrependInt32Slot(3, index, -1)

def AddIndex(builder, index):
    AddTrackOpAddIndex(builder, index)

def AddTrackOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return AddTrackOpEnd(builder)
