# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AttachAssetOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AttachAssetOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAttachAssetOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AttachAssetOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AttachAssetOp
    def AssetId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AttachAssetOp
    def Sha256(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AttachAssetOp
    def MediaType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AttachAssetOp
    def RelPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AttachAssetOp
    def Channels(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AttachAssetOp
    def DurationTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def AttachAssetOpStart(builder):
    builder.StartObject(6)

def Start(builder):
    AttachAssetOpStart(builder)

def AttachAssetOpAddAssetId(builder, assetId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(assetId), 0)

def AddAssetId(builder, assetId):
    AttachAssetOpAddAssetId(builder, assetId)

def AttachAssetOpAddSha256(builder, sha256):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(sha256), 0)

def AddSha256(builder, sha256):
    AttachAssetOpAddSha256(builder, sha256)

def AttachAssetOpAddMediaType(builder, mediaType):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(mediaType), 0)

def AddMediaType(builder, mediaType):
    AttachAssetOpAddMediaType(builder, mediaType)

def AttachAssetOpAddRelPath(builder, relPath):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(relPath), 0)

def AddRelPath(builder, relPath):
    AttachAssetOpAddRelPath(builder, relPath)

def AttachAssetOpAddChannels(builder, channels):
    builder.PrependInt32Slot(4, channels, 0)

def AddChannels(builder, channels):
    AttachAssetOpAddChannels(builder, channels)

def AttachAssetOpAddDurationTicks(builder, durationTicks):
    builder.PrependInt64Slot(5, durationTicks, 0)

def AddDurationTicks(builder, durationTicks):
    AttachAssetOpAddDurationTicks(builder, durationTicks)

def AttachAssetOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return AttachAssetOpEnd(builder)
