# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClockSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClockSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClockSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClockSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClockSnapshot
    def ProjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ClockSnapshot
    def EngineEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ClockSnapshot
    def TimelineSample(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ClockSnapshot
    def DeviceSampleCounter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ClockSnapshot
    def SampleRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ClockSnapshot
    def TransportState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ClockSnapshot
    def LoopStartTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ClockSnapshot
    def LoopEndTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ClockSnapshot
    def TempoMapRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ClockSnapshot
    def Sequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ClockSnapshot
    def HostClockNs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ClockSnapshotStart(builder):
    builder.StartObject(11)

def Start(builder):
    ClockSnapshotStart(builder)

def ClockSnapshotAddProjectId(builder, projectId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(projectId), 0)

def AddProjectId(builder, projectId):
    ClockSnapshotAddProjectId(builder, projectId)

def ClockSnapshotAddEngineEpoch(builder, engineEpoch):
    builder.PrependUint64Slot(1, engineEpoch, 0)

def AddEngineEpoch(builder, engineEpoch):
    ClockSnapshotAddEngineEpoch(builder, engineEpoch)

def ClockSnapshotAddTimelineSample(builder, timelineSample):
    builder.PrependInt64Slot(2, timelineSample, 0)

def AddTimelineSample(builder, timelineSample):
    ClockSnapshotAddTimelineSample(builder, timelineSample)

def ClockSnapshotAddDeviceSampleCounter(builder, deviceSampleCounter):
    builder.PrependInt64Slot(3, deviceSampleCounter, 0)

def AddDeviceSampleCounter(builder, deviceSampleCounter):
    ClockSnapshotAddDeviceSampleCounter(builder, deviceSampleCounter)

def ClockSnapshotAddSampleRate(builder, sampleRate):
    builder.PrependUint32Slot(4, sampleRate, 0)

def AddSampleRate(builder, sampleRate):
    ClockSnapshotAddSampleRate(builder, sampleRate)

def ClockSnapshotAddTransportState(builder, transportState):
    builder.PrependInt8Slot(5, transportState, 0)

def AddTransportState(builder, transportState):
    ClockSnapshotAddTransportState(builder, transportState)

def ClockSnapshotAddLoopStartTicks(builder, loopStartTicks):
    builder.PrependInt64Slot(6, loopStartTicks, 0)

def AddLoopStartTicks(builder, loopStartTicks):
    ClockSnapshotAddLoopStartTicks(builder, loopStartTicks)

def ClockSnapshotAddLoopEndTicks(builder, loopEndTicks):
    builder.PrependInt64Slot(7, loopEndTicks, 0)

def AddLoopEndTicks(builder, loopEndTicks):
    ClockSnapshotAddLoopEndTicks(builder, loopEndTicks)

def ClockSnapshotAddTempoMapRevision(builder, tempoMapRevision):
    builder.PrependUint64Slot(8, tempoMapRevision, 0)

def AddTempoMapRevision(builder, tempoMapRevision):
    ClockSnapshotAddTempoMapRevision(builder, tempoMapRevision)

def ClockSnapshotAddSequence(builder, sequence):
    builder.PrependUint64Slot(9, sequence, 0)

def AddSequence(builder, sequence):
    ClockSnapshotAddSequence(builder, sequence)

def ClockSnapshotAddHostClockNs(builder, hostClockNs):
    builder.PrependUint64Slot(10, hostClockNs, 0)

def AddHostClockNs(builder, hostClockNs):
    ClockSnapshotAddHostClockNs(builder, hostClockNs)

def ClockSnapshotEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClockSnapshotEnd(builder)
