# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CloseProjectOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CloseProjectOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCloseProjectOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CloseProjectOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def CloseProjectOpStart(builder):
    builder.StartObject(0)

def Start(builder):
    CloseProjectOpStart(builder)

def CloseProjectOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return CloseProjectOpEnd(builder)
