# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClosePluginEditorOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClosePluginEditorOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClosePluginEditorOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClosePluginEditorOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClosePluginEditorOp
    def PluginInstanceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ClosePluginEditorOpStart(builder):
    builder.StartObject(1)

def Start(builder):
    ClosePluginEditorOpStart(builder)

def ClosePluginEditorOpAddPluginInstanceId(builder, pluginInstanceId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pluginInstanceId), 0)

def AddPluginInstanceId(builder, pluginInstanceId):
    ClosePluginEditorOpAddPluginInstanceId(builder, pluginInstanceId)

def ClosePluginEditorOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClosePluginEditorOpEnd(builder)
