# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CommandReceipt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CommandReceipt()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCommandReceipt(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CommandReceipt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CommandReceipt
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommandReceipt
    def TransactionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommandReceipt
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # CommandReceipt
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # CommandReceipt
    def Revision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CommandReceipt
    def EngineEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CommandReceipt
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CommandReceipt
    def PayloadHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CommandReceiptStart(builder):
    builder.StartObject(8)

def Start(builder):
    CommandReceiptStart(builder)

def CommandReceiptAddCommandId(builder, commandId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(commandId), 0)

def AddCommandId(builder, commandId):
    CommandReceiptAddCommandId(builder, commandId)

def CommandReceiptAddTransactionId(builder, transactionId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(transactionId), 0)

def AddTransactionId(builder, transactionId):
    CommandReceiptAddTransactionId(builder, transactionId)

def CommandReceiptAddStatus(builder, status):
    builder.PrependInt8Slot(2, status, 0)

def AddStatus(builder, status):
    CommandReceiptAddStatus(builder, status)

def CommandReceiptAddError(builder, error):
    builder.PrependUint16Slot(3, error, 0)

def AddError(builder, error):
    CommandReceiptAddError(builder, error)

def CommandReceiptAddRevision(builder, revision):
    builder.PrependUint64Slot(4, revision, 0)

def AddRevision(builder, revision):
    CommandReceiptAddRevision(builder, revision)

def CommandReceiptAddEngineEpoch(builder, engineEpoch):
    builder.PrependUint64Slot(5, engineEpoch, 0)

def AddEngineEpoch(builder, engineEpoch):
    CommandReceiptAddEngineEpoch(builder, engineEpoch)

def CommandReceiptAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    CommandReceiptAddMessage(builder, message)

def CommandReceiptAddPayloadHash(builder, payloadHash):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(payloadHash), 0)

def AddPayloadHash(builder, payloadHash):
    CommandReceiptAddPayloadHash(builder, payloadHash)

def CommandReceiptEnd(builder):
    return builder.EndObject()

def End(builder):
    return CommandReceiptEnd(builder)
