# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ControlEnvelope(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ControlEnvelope()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsControlEnvelope(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ControlEnvelope
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ControlEnvelope
    def FrameType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ControlEnvelope
    def Frame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ControlEnvelopeStart(builder):
    builder.StartObject(2)

def Start(builder):
    ControlEnvelopeStart(builder)

def ControlEnvelopeAddFrameType(builder, frameType):
    builder.PrependUint8Slot(0, frameType, 0)

def AddFrameType(builder, frameType):
    ControlEnvelopeAddFrameType(builder, frameType)

def ControlEnvelopeAddFrame(builder, frame):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(frame), 0)

def AddFrame(builder, frame):
    ControlEnvelopeAddFrame(builder, frame)

def ControlEnvelopeEnd(builder):
    return builder.EndObject()

def End(builder):
    return ControlEnvelopeEnd(builder)
