# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

class ControlRequest(object):
    NONE = 0
    PersistentCommand = 1
    TransportRequest = 2
    ReadRequest = 3
    PluginScanRequest = 4
