# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

class ControlEvent(object):
    NONE = 0
    CommandReceipt = 1
    ReadResponse = 2
    PluginScanResult = 3
