# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CreateProjectOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CreateProjectOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCreateProjectOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CreateProjectOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CreateProjectOp
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CreateProjectOp
    def ContainerDir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CreateProjectOp
    def SampleRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 48000

    # CreateProjectOp
    def InitialBpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 120.0

def CreateProjectOpStart(builder):
    builder.StartObject(4)

def Start(builder):
    CreateProjectOpStart(builder)

def CreateProjectOpAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    CreateProjectOpAddName(builder, name)

def CreateProjectOpAddContainerDir(builder, containerDir):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(containerDir), 0)

def AddContainerDir(builder, containerDir):
    CreateProjectOpAddContainerDir(builder, containerDir)

def CreateProjectOpAddSampleRate(builder, sampleRate):
    builder.PrependUint32Slot(2, sampleRate, 48000)

def AddSampleRate(builder, sampleRate):
    CreateProjectOpAddSampleRate(builder, sampleRate)

def CreateProjectOpAddInitialBpm(builder, initialBpm):
    builder.PrependFloat32Slot(3, initialBpm, 120.0)

def AddInitialBpm(builder, initialBpm):
    CreateProjectOpAddInitialBpm(builder, initialBpm)

def CreateProjectOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return CreateProjectOpEnd(builder)
