# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

class ErrorCode(object):
    NONE = 0
    BAD_REQUEST = 1
    UNSUPPORTED_VERSION = 2
    UNSUPPORTED_CAPABILITY = 3
    NOT_AUTHORIZED = 4
    NOT_FOUND = 5
    STALE_REVISION = 6
    STALE_EPOCH = 7
    COMMAND_ID_REUSE = 8
    BUSY = 9
    DEVICE_UNAVAILABLE = 10
    ASSET_MISSING = 11
    PLUGIN_UNAVAILABLE = 12
    DISK_FULL = 13
    WORKER_FAILED = 14
    CANCELLED = 15
    OUTCOME_UNKNOWN = 16
