# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InsertMidiClipOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InsertMidiClipOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInsertMidiClipOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InsertMidiClipOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InsertMidiClipOp
    def ClipId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InsertMidiClipOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InsertMidiClipOp
    def StartTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # InsertMidiClipOp
    def LengthTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def InsertMidiClipOpStart(builder):
    builder.StartObject(4)

def Start(builder):
    InsertMidiClipOpStart(builder)

def InsertMidiClipOpAddClipId(builder, clipId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clipId), 0)

def AddClipId(builder, clipId):
    InsertMidiClipOpAddClipId(builder, clipId)

def InsertMidiClipOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    InsertMidiClipOpAddTrackId(builder, trackId)

def InsertMidiClipOpAddStartTicks(builder, startTicks):
    builder.PrependInt64Slot(2, startTicks, 0)

def AddStartTicks(builder, startTicks):
    InsertMidiClipOpAddStartTicks(builder, startTicks)

def InsertMidiClipOpAddLengthTicks(builder, lengthTicks):
    builder.PrependInt64Slot(3, lengthTicks, 0)

def AddLengthTicks(builder, lengthTicks):
    InsertMidiClipOpAddLengthTicks(builder, lengthTicks)

def InsertMidiClipOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return InsertMidiClipOpEnd(builder)
