# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InsertAudioClipOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InsertAudioClipOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInsertAudioClipOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InsertAudioClipOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InsertAudioClipOp
    def ClipId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InsertAudioClipOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InsertAudioClipOp
    def AssetId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InsertAudioClipOp
    def StartTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # InsertAudioClipOp
    def LengthTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # InsertAudioClipOp
    def OffsetTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def InsertAudioClipOpStart(builder):
    builder.StartObject(6)

def Start(builder):
    InsertAudioClipOpStart(builder)

def InsertAudioClipOpAddClipId(builder, clipId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clipId), 0)

def AddClipId(builder, clipId):
    InsertAudioClipOpAddClipId(builder, clipId)

def InsertAudioClipOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    InsertAudioClipOpAddTrackId(builder, trackId)

def InsertAudioClipOpAddAssetId(builder, assetId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(assetId), 0)

def AddAssetId(builder, assetId):
    InsertAudioClipOpAddAssetId(builder, assetId)

def InsertAudioClipOpAddStartTicks(builder, startTicks):
    builder.PrependInt64Slot(3, startTicks, 0)

def AddStartTicks(builder, startTicks):
    InsertAudioClipOpAddStartTicks(builder, startTicks)

def InsertAudioClipOpAddLengthTicks(builder, lengthTicks):
    builder.PrependInt64Slot(4, lengthTicks, 0)

def AddLengthTicks(builder, lengthTicks):
    InsertAudioClipOpAddLengthTicks(builder, lengthTicks)

def InsertAudioClipOpAddOffsetTicks(builder, offsetTicks):
    builder.PrependInt64Slot(5, offsetTicks, 0)

def AddOffsetTicks(builder, offsetTicks):
    InsertAudioClipOpAddOffsetTicks(builder, offsetTicks)

def InsertAudioClipOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return InsertAudioClipOpEnd(builder)
