# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InsertNoteOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InsertNoteOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInsertNoteOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InsertNoteOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InsertNoteOp
    def ClipId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InsertNoteOp
    def NoteId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InsertNoteOp
    def Pitch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # InsertNoteOp
    def Velocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # InsertNoteOp
    def StartTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # InsertNoteOp
    def LengthTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def InsertNoteOpStart(builder):
    builder.StartObject(6)

def Start(builder):
    InsertNoteOpStart(builder)

def InsertNoteOpAddClipId(builder, clipId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clipId), 0)

def AddClipId(builder, clipId):
    InsertNoteOpAddClipId(builder, clipId)

def InsertNoteOpAddNoteId(builder, noteId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(noteId), 0)

def AddNoteId(builder, noteId):
    InsertNoteOpAddNoteId(builder, noteId)

def InsertNoteOpAddPitch(builder, pitch):
    builder.PrependUint8Slot(2, pitch, 0)

def AddPitch(builder, pitch):
    InsertNoteOpAddPitch(builder, pitch)

def InsertNoteOpAddVelocity(builder, velocity):
    builder.PrependUint8Slot(3, velocity, 0)

def AddVelocity(builder, velocity):
    InsertNoteOpAddVelocity(builder, velocity)

def InsertNoteOpAddStartTicks(builder, startTicks):
    builder.PrependInt64Slot(4, startTicks, 0)

def AddStartTicks(builder, startTicks):
    InsertNoteOpAddStartTicks(builder, startTicks)

def InsertNoteOpAddLengthTicks(builder, lengthTicks):
    builder.PrependInt64Slot(5, lengthTicks, 0)

def AddLengthTicks(builder, lengthTicks):
    InsertNoteOpAddLengthTicks(builder, lengthTicks)

def InsertNoteOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return InsertNoteOpEnd(builder)
