# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InsertPluginOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InsertPluginOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInsertPluginOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InsertPluginOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InsertPluginOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InsertPluginOp
    def Slot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # InsertPluginOp
    def PluginInstanceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InsertPluginOp
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InsertPluginOp
    def PluginUid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def InsertPluginOpStart(builder):
    builder.StartObject(5)

def Start(builder):
    InsertPluginOpStart(builder)

def InsertPluginOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    InsertPluginOpAddTrackId(builder, trackId)

def InsertPluginOpAddSlot(builder, slot):
    builder.PrependInt32Slot(1, slot, -1)

def AddSlot(builder, slot):
    InsertPluginOpAddSlot(builder, slot)

def InsertPluginOpAddPluginInstanceId(builder, pluginInstanceId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(pluginInstanceId), 0)

def AddPluginInstanceId(builder, pluginInstanceId):
    InsertPluginOpAddPluginInstanceId(builder, pluginInstanceId)

def InsertPluginOpAddFormat(builder, format):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(format), 0)

def AddFormat(builder, format):
    InsertPluginOpAddFormat(builder, format)

def InsertPluginOpAddPluginUid(builder, pluginUid):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(pluginUid), 0)

def AddPluginUid(builder, pluginUid):
    InsertPluginOpAddPluginUid(builder, pluginUid)

def InsertPluginOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return InsertPluginOpEnd(builder)
