# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MeterFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MeterFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMeterFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MeterFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MeterFrame
    def ProjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MeterFrame
    def EngineEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # MeterFrame
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MeterFrame
    def PeakL(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # MeterFrame
    def PeakR(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # MeterFrame
    def RmsL(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # MeterFrame
    def RmsR(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # MeterFrame
    def Clipped(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # MeterFrame
    def Sequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def MeterFrameStart(builder):
    builder.StartObject(9)

def Start(builder):
    MeterFrameStart(builder)

def MeterFrameAddProjectId(builder, projectId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(projectId), 0)

def AddProjectId(builder, projectId):
    MeterFrameAddProjectId(builder, projectId)

def MeterFrameAddEngineEpoch(builder, engineEpoch):
    builder.PrependUint64Slot(1, engineEpoch, 0)

def AddEngineEpoch(builder, engineEpoch):
    MeterFrameAddEngineEpoch(builder, engineEpoch)

def MeterFrameAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    MeterFrameAddTrackId(builder, trackId)

def MeterFrameAddPeakL(builder, peakL):
    builder.PrependFloat32Slot(3, peakL, 0.0)

def AddPeakL(builder, peakL):
    MeterFrameAddPeakL(builder, peakL)

def MeterFrameAddPeakR(builder, peakR):
    builder.PrependFloat32Slot(4, peakR, 0.0)

def AddPeakR(builder, peakR):
    MeterFrameAddPeakR(builder, peakR)

def MeterFrameAddRmsL(builder, rmsL):
    builder.PrependFloat32Slot(5, rmsL, 0.0)

def AddRmsL(builder, rmsL):
    MeterFrameAddRmsL(builder, rmsL)

def MeterFrameAddRmsR(builder, rmsR):
    builder.PrependFloat32Slot(6, rmsR, 0.0)

def AddRmsR(builder, rmsR):
    MeterFrameAddRmsR(builder, rmsR)

def MeterFrameAddClipped(builder, clipped):
    builder.PrependBoolSlot(7, clipped, 0)

def AddClipped(builder, clipped):
    MeterFrameAddClipped(builder, clipped)

def MeterFrameAddSequence(builder, sequence):
    builder.PrependUint64Slot(8, sequence, 0)

def AddSequence(builder, sequence):
    MeterFrameAddSequence(builder, sequence)

def MeterFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return MeterFrameEnd(builder)
