# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MoveClipOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MoveClipOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMoveClipOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MoveClipOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MoveClipOp
    def ClipId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MoveClipOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # MoveClipOp
    def StartTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def MoveClipOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    MoveClipOpStart(builder)

def MoveClipOpAddClipId(builder, clipId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clipId), 0)

def AddClipId(builder, clipId):
    MoveClipOpAddClipId(builder, clipId)

def MoveClipOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    MoveClipOpAddTrackId(builder, trackId)

def MoveClipOpAddStartTicks(builder, startTicks):
    builder.PrependInt64Slot(2, startTicks, 0)

def AddStartTicks(builder, startTicks):
    MoveClipOpAddStartTicks(builder, startTicks)

def MoveClipOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return MoveClipOpEnd(builder)
