# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OpenProjectOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OpenProjectOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOpenProjectOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OpenProjectOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OpenProjectOp
    def ContainerDir(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def OpenProjectOpStart(builder):
    builder.StartObject(1)

def Start(builder):
    OpenProjectOpStart(builder)

def OpenProjectOpAddContainerDir(builder, containerDir):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(containerDir), 0)

def AddContainerDir(builder, containerDir):
    OpenProjectOpAddContainerDir(builder, containerDir)

def OpenProjectOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return OpenProjectOpEnd(builder)
