# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PersistentCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PersistentCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPersistentCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PersistentCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PersistentCommand
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PersistentCommand
    def TransactionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PersistentCommand
    def ProjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PersistentCommand
    def EngineEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PersistentCommand
    def ExpectedRevision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PersistentCommand
    def OpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PersistentCommand
    def Op(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def PersistentCommandStart(builder):
    builder.StartObject(7)

def Start(builder):
    PersistentCommandStart(builder)

def PersistentCommandAddCommandId(builder, commandId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(commandId), 0)

def AddCommandId(builder, commandId):
    PersistentCommandAddCommandId(builder, commandId)

def PersistentCommandAddTransactionId(builder, transactionId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(transactionId), 0)

def AddTransactionId(builder, transactionId):
    PersistentCommandAddTransactionId(builder, transactionId)

def PersistentCommandAddProjectId(builder, projectId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(projectId), 0)

def AddProjectId(builder, projectId):
    PersistentCommandAddProjectId(builder, projectId)

def PersistentCommandAddEngineEpoch(builder, engineEpoch):
    builder.PrependUint64Slot(3, engineEpoch, 0)

def AddEngineEpoch(builder, engineEpoch):
    PersistentCommandAddEngineEpoch(builder, engineEpoch)

def PersistentCommandAddExpectedRevision(builder, expectedRevision):
    builder.PrependUint64Slot(4, expectedRevision, 0)

def AddExpectedRevision(builder, expectedRevision):
    PersistentCommandAddExpectedRevision(builder, expectedRevision)

def PersistentCommandAddOpType(builder, opType):
    builder.PrependUint8Slot(5, opType, 0)

def AddOpType(builder, opType):
    PersistentCommandAddOpType(builder, opType)

def PersistentCommandAddOp(builder, op):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(op), 0)

def AddOp(builder, op):
    PersistentCommandAddOp(builder, op)

def PersistentCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return PersistentCommandEnd(builder)
