# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

class PersistentOp(object):
    NONE = 0
    CreateProjectOp = 1
    OpenProjectOp = 2
    CloseProjectOp = 3
    AddTrackOp = 4
    RemoveTrackOp = 5
    SetTrackNameOp = 6
    SetTrackGainOp = 7
    SetTrackPanOp = 8
    SetTrackMuteOp = 9
    SetTrackSoloOp = 10
    InsertAudioClipOp = 11
    InsertMidiClipOp = 12
    RemoveClipOp = 13
    MoveClipOp = 14
    TrimClipOp = 15
    SplitClipOp = 16
    InsertNoteOp = 17
    RemoveNoteOp = 18
    SetNoteOp = 19
    SetTempoOp = 20
    SetTimeSignatureOp = 21
    SetLoopRangeOp = 22
    SaveProjectOp = 23
    CreateCheckpointOp = 24
    UndoOp = 25
    RedoOp = 26
    AttachAssetOp = 27
    InsertPluginOp = 28
    RemovePluginOp = 29
    SetPluginParamOp = 30
    OpenPluginEditorOp = 31
    ClosePluginEditorOp = 32
