# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PluginScanRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PluginScanRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPluginScanRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PluginScanRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PluginScanRequest
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginScanRequest
    def PluginPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginScanRequest
    def Format(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PluginScanRequestStart(builder):
    builder.StartObject(3)

def Start(builder):
    PluginScanRequestStart(builder)

def PluginScanRequestAddRequestId(builder, requestId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)

def AddRequestId(builder, requestId):
    PluginScanRequestAddRequestId(builder, requestId)

def PluginScanRequestAddPluginPath(builder, pluginPath):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(pluginPath), 0)

def AddPluginPath(builder, pluginPath):
    PluginScanRequestAddPluginPath(builder, pluginPath)

def PluginScanRequestAddFormat(builder, format):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(format), 0)

def AddFormat(builder, format):
    PluginScanRequestAddFormat(builder, format)

def PluginScanRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return PluginScanRequestEnd(builder)
