# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PluginScanResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PluginScanResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPluginScanResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PluginScanResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PluginScanResult
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginScanResult
    def Ok(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # PluginScanResult
    def Quarantined(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # PluginScanResult
    def PluginUid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginScanResult
    def BinarySha256(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginScanResult
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginScanResult
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginScanResult
    def Arch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginScanResult
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # PluginScanResult
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PluginScanResultStart(builder):
    builder.StartObject(10)

def Start(builder):
    PluginScanResultStart(builder)

def PluginScanResultAddRequestId(builder, requestId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)

def AddRequestId(builder, requestId):
    PluginScanResultAddRequestId(builder, requestId)

def PluginScanResultAddOk(builder, ok):
    builder.PrependBoolSlot(1, ok, 0)

def AddOk(builder, ok):
    PluginScanResultAddOk(builder, ok)

def PluginScanResultAddQuarantined(builder, quarantined):
    builder.PrependBoolSlot(2, quarantined, 0)

def AddQuarantined(builder, quarantined):
    PluginScanResultAddQuarantined(builder, quarantined)

def PluginScanResultAddPluginUid(builder, pluginUid):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(pluginUid), 0)

def AddPluginUid(builder, pluginUid):
    PluginScanResultAddPluginUid(builder, pluginUid)

def PluginScanResultAddBinarySha256(builder, binarySha256):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(binarySha256), 0)

def AddBinarySha256(builder, binarySha256):
    PluginScanResultAddBinarySha256(builder, binarySha256)

def PluginScanResultAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    PluginScanResultAddName(builder, name)

def PluginScanResultAddVersion(builder, version):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(version), 0)

def AddVersion(builder, version):
    PluginScanResultAddVersion(builder, version)

def PluginScanResultAddArch(builder, arch):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(arch), 0)

def AddArch(builder, arch):
    PluginScanResultAddArch(builder, arch)

def PluginScanResultAddError(builder, error):
    builder.PrependUint16Slot(8, error, 0)

def AddError(builder, error):
    PluginScanResultAddError(builder, error)

def PluginScanResultAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    PluginScanResultAddMessage(builder, message)

def PluginScanResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return PluginScanResultEnd(builder)
