# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReadRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReadRequest
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReadRequest
    def ProjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReadRequest
    def View(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ReadRequest
    def Cursor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReadRequest
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ReadRequest
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReadRequest
    def StartTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return -1

    # ReadRequest
    def EndTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return -1

def ReadRequestStart(builder):
    builder.StartObject(8)

def Start(builder):
    ReadRequestStart(builder)

def ReadRequestAddRequestId(builder, requestId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)

def AddRequestId(builder, requestId):
    ReadRequestAddRequestId(builder, requestId)

def ReadRequestAddProjectId(builder, projectId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(projectId), 0)

def AddProjectId(builder, projectId):
    ReadRequestAddProjectId(builder, projectId)

def ReadRequestAddView(builder, view):
    builder.PrependInt8Slot(2, view, 0)

def AddView(builder, view):
    ReadRequestAddView(builder, view)

def ReadRequestAddCursor(builder, cursor):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(cursor), 0)

def AddCursor(builder, cursor):
    ReadRequestAddCursor(builder, cursor)

def ReadRequestAddLimit(builder, limit):
    builder.PrependUint32Slot(4, limit, 0)

def AddLimit(builder, limit):
    ReadRequestAddLimit(builder, limit)

def ReadRequestAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    ReadRequestAddTrackId(builder, trackId)

def ReadRequestAddStartTicks(builder, startTicks):
    builder.PrependInt64Slot(6, startTicks, -1)

def AddStartTicks(builder, startTicks):
    ReadRequestAddStartTicks(builder, startTicks)

def ReadRequestAddEndTicks(builder, endTicks):
    builder.PrependInt64Slot(7, endTicks, -1)

def AddEndTicks(builder, endTicks):
    ReadRequestAddEndTicks(builder, endTicks)

def ReadRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReadRequestEnd(builder)
