# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReadResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReadResponse
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReadResponse
    def Revision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReadResponse
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from voidproto.ReadItem import ReadItem
            obj = ReadItem()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ReadResponse
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ReadResponse
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ReadResponse
    def NextCursor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReadResponse
    def Done(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ReadResponse
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def ReadResponseStart(builder):
    builder.StartObject(6)

def Start(builder):
    ReadResponseStart(builder)

def ReadResponseAddRequestId(builder, requestId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)

def AddRequestId(builder, requestId):
    ReadResponseAddRequestId(builder, requestId)

def ReadResponseAddRevision(builder, revision):
    builder.PrependUint64Slot(1, revision, 0)

def AddRevision(builder, revision):
    ReadResponseAddRevision(builder, revision)

def ReadResponseAddItems(builder, items):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)

def AddItems(builder, items):
    ReadResponseAddItems(builder, items)

def ReadResponseStartItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartItemsVector(builder, numElems):
    return ReadResponseStartItemsVector(builder, numElems)

def ReadResponseAddNextCursor(builder, nextCursor):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(nextCursor), 0)

def AddNextCursor(builder, nextCursor):
    ReadResponseAddNextCursor(builder, nextCursor)

def ReadResponseAddDone(builder, done):
    builder.PrependBoolSlot(4, done, 0)

def AddDone(builder, done):
    ReadResponseAddDone(builder, done)

def ReadResponseAddError(builder, error):
    builder.PrependUint16Slot(5, error, 0)

def AddError(builder, error):
    ReadResponseAddError(builder, error)

def ReadResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReadResponseEnd(builder)
