# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReadItem(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadItem()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadItem(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadItem
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReadItem
    def ObjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReadItem
    def SummaryJson(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ReadItemStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReadItemStart(builder)

def ReadItemAddObjectId(builder, objectId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objectId), 0)

def AddObjectId(builder, objectId):
    ReadItemAddObjectId(builder, objectId)

def ReadItemAddSummaryJson(builder, summaryJson):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(summaryJson), 0)

def AddSummaryJson(builder, summaryJson):
    ReadItemAddSummaryJson(builder, summaryJson)

def ReadItemEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReadItemEnd(builder)
