# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RemoveClipOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RemoveClipOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRemoveClipOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RemoveClipOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RemoveClipOp
    def ClipId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RemoveClipOpStart(builder):
    builder.StartObject(1)

def Start(builder):
    RemoveClipOpStart(builder)

def RemoveClipOpAddClipId(builder, clipId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clipId), 0)

def AddClipId(builder, clipId):
    RemoveClipOpAddClipId(builder, clipId)

def RemoveClipOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return RemoveClipOpEnd(builder)
