# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RemoveTrackOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RemoveTrackOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRemoveTrackOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RemoveTrackOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RemoveTrackOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RemoveTrackOpStart(builder):
    builder.StartObject(1)

def Start(builder):
    RemoveTrackOpStart(builder)

def RemoveTrackOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    RemoveTrackOpAddTrackId(builder, trackId)

def RemoveTrackOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return RemoveTrackOpEnd(builder)
