# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RemoveNoteOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RemoveNoteOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRemoveNoteOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RemoveNoteOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RemoveNoteOp
    def ClipId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RemoveNoteOp
    def NoteId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RemoveNoteOpStart(builder):
    builder.StartObject(2)

def Start(builder):
    RemoveNoteOpStart(builder)

def RemoveNoteOpAddClipId(builder, clipId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clipId), 0)

def AddClipId(builder, clipId):
    RemoveNoteOpAddClipId(builder, clipId)

def RemoveNoteOpAddNoteId(builder, noteId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(noteId), 0)

def AddNoteId(builder, noteId):
    RemoveNoteOpAddNoteId(builder, noteId)

def RemoveNoteOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return RemoveNoteOpEnd(builder)
