# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RemovePluginOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RemovePluginOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRemovePluginOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RemovePluginOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RemovePluginOp
    def PluginInstanceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RemovePluginOpStart(builder):
    builder.StartObject(1)

def Start(builder):
    RemovePluginOpStart(builder)

def RemovePluginOpAddPluginInstanceId(builder, pluginInstanceId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pluginInstanceId), 0)

def AddPluginInstanceId(builder, pluginInstanceId):
    RemovePluginOpAddPluginInstanceId(builder, pluginInstanceId)

def RemovePluginOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return RemovePluginOpEnd(builder)
