# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RequestFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequestFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RequestFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestFrame
    def RequestType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # RequestFrame
    def Request(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def RequestFrameStart(builder):
    builder.StartObject(2)

def Start(builder):
    RequestFrameStart(builder)

def RequestFrameAddRequestType(builder, requestType):
    builder.PrependUint8Slot(0, requestType, 0)

def AddRequestType(builder, requestType):
    RequestFrameAddRequestType(builder, requestType)

def RequestFrameAddRequest(builder, request):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(request), 0)

def AddRequest(builder, request):
    RequestFrameAddRequest(builder, request)

def RequestFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return RequestFrameEnd(builder)
