# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SaveResultEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SaveResultEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSaveResultEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SaveResultEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SaveResultEvent
    def ProjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SaveResultEvent
    def CommandId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SaveResultEvent
    def Status(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # SaveResultEvent
    def Revision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # SaveResultEvent
    def CheckpointId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SaveResultEvent
    def ManifestSha256(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SaveResultEvent
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # SaveResultEvent
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SaveResultEventStart(builder):
    builder.StartObject(8)

def Start(builder):
    SaveResultEventStart(builder)

def SaveResultEventAddProjectId(builder, projectId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(projectId), 0)

def AddProjectId(builder, projectId):
    SaveResultEventAddProjectId(builder, projectId)

def SaveResultEventAddCommandId(builder, commandId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(commandId), 0)

def AddCommandId(builder, commandId):
    SaveResultEventAddCommandId(builder, commandId)

def SaveResultEventAddStatus(builder, status):
    builder.PrependInt8Slot(2, status, 0)

def AddStatus(builder, status):
    SaveResultEventAddStatus(builder, status)

def SaveResultEventAddRevision(builder, revision):
    builder.PrependUint64Slot(3, revision, 0)

def AddRevision(builder, revision):
    SaveResultEventAddRevision(builder, revision)

def SaveResultEventAddCheckpointId(builder, checkpointId):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(checkpointId), 0)

def AddCheckpointId(builder, checkpointId):
    SaveResultEventAddCheckpointId(builder, checkpointId)

def SaveResultEventAddManifestSha256(builder, manifestSha256):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(manifestSha256), 0)

def AddManifestSha256(builder, manifestSha256):
    SaveResultEventAddManifestSha256(builder, manifestSha256)

def SaveResultEventAddError(builder, error):
    builder.PrependUint16Slot(6, error, 0)

def AddError(builder, error):
    SaveResultEventAddError(builder, error)

def SaveResultEventAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    SaveResultEventAddMessage(builder, message)

def SaveResultEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return SaveResultEventEnd(builder)
