# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetLoopRangeOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetLoopRangeOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetLoopRangeOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetLoopRangeOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetLoopRangeOp
    def StartTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SetLoopRangeOp
    def EndTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SetLoopRangeOp
    def Enabled(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SetLoopRangeOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    SetLoopRangeOpStart(builder)

def SetLoopRangeOpAddStartTicks(builder, startTicks):
    builder.PrependInt64Slot(0, startTicks, 0)

def AddStartTicks(builder, startTicks):
    SetLoopRangeOpAddStartTicks(builder, startTicks)

def SetLoopRangeOpAddEndTicks(builder, endTicks):
    builder.PrependInt64Slot(1, endTicks, 0)

def AddEndTicks(builder, endTicks):
    SetLoopRangeOpAddEndTicks(builder, endTicks)

def SetLoopRangeOpAddEnabled(builder, enabled):
    builder.PrependBoolSlot(2, enabled, 0)

def AddEnabled(builder, enabled):
    SetLoopRangeOpAddEnabled(builder, enabled)

def SetLoopRangeOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetLoopRangeOpEnd(builder)
