# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetNoteOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetNoteOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetNoteOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetNoteOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetNoteOp
    def ClipId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetNoteOp
    def NoteId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetNoteOp
    def Pitch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # SetNoteOp
    def Velocity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

    # SetNoteOp
    def StartTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return -1

    # SetNoteOp
    def LengthTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return -1

def SetNoteOpStart(builder):
    builder.StartObject(6)

def Start(builder):
    SetNoteOpStart(builder)

def SetNoteOpAddClipId(builder, clipId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clipId), 0)

def AddClipId(builder, clipId):
    SetNoteOpAddClipId(builder, clipId)

def SetNoteOpAddNoteId(builder, noteId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(noteId), 0)

def AddNoteId(builder, noteId):
    SetNoteOpAddNoteId(builder, noteId)

def SetNoteOpAddPitch(builder, pitch):
    builder.PrependInt32Slot(2, pitch, -1)

def AddPitch(builder, pitch):
    SetNoteOpAddPitch(builder, pitch)

def SetNoteOpAddVelocity(builder, velocity):
    builder.PrependInt32Slot(3, velocity, -1)

def AddVelocity(builder, velocity):
    SetNoteOpAddVelocity(builder, velocity)

def SetNoteOpAddStartTicks(builder, startTicks):
    builder.PrependInt64Slot(4, startTicks, -1)

def AddStartTicks(builder, startTicks):
    SetNoteOpAddStartTicks(builder, startTicks)

def SetNoteOpAddLengthTicks(builder, lengthTicks):
    builder.PrependInt64Slot(5, lengthTicks, -1)

def AddLengthTicks(builder, lengthTicks):
    SetNoteOpAddLengthTicks(builder, lengthTicks)

def SetNoteOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetNoteOpEnd(builder)
