# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetPluginParamOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetPluginParamOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetPluginParamOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetPluginParamOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetPluginParamOp
    def PluginInstanceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetPluginParamOp
    def ParamId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetPluginParamOp
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetPluginParamOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    SetPluginParamOpStart(builder)

def SetPluginParamOpAddPluginInstanceId(builder, pluginInstanceId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pluginInstanceId), 0)

def AddPluginInstanceId(builder, pluginInstanceId):
    SetPluginParamOpAddPluginInstanceId(builder, pluginInstanceId)

def SetPluginParamOpAddParamId(builder, paramId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(paramId), 0)

def AddParamId(builder, paramId):
    SetPluginParamOpAddParamId(builder, paramId)

def SetPluginParamOpAddValue(builder, value):
    builder.PrependFloat32Slot(2, value, 0.0)

def AddValue(builder, value):
    SetPluginParamOpAddValue(builder, value)

def SetPluginParamOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetPluginParamOpEnd(builder)
