# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetTimeSignatureOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetTimeSignatureOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetTimeSignatureOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetTimeSignatureOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetTimeSignatureOp
    def AtTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SetTimeSignatureOp
    def Numerator(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SetTimeSignatureOp
    def Denominator(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def SetTimeSignatureOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    SetTimeSignatureOpStart(builder)

def SetTimeSignatureOpAddAtTicks(builder, atTicks):
    builder.PrependInt64Slot(0, atTicks, 0)

def AddAtTicks(builder, atTicks):
    SetTimeSignatureOpAddAtTicks(builder, atTicks)

def SetTimeSignatureOpAddNumerator(builder, numerator):
    builder.PrependUint8Slot(1, numerator, 0)

def AddNumerator(builder, numerator):
    SetTimeSignatureOpAddNumerator(builder, numerator)

def SetTimeSignatureOpAddDenominator(builder, denominator):
    builder.PrependUint8Slot(2, denominator, 0)

def AddDenominator(builder, denominator):
    SetTimeSignatureOpAddDenominator(builder, denominator)

def SetTimeSignatureOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetTimeSignatureOpEnd(builder)
