# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetTempoOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetTempoOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetTempoOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetTempoOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetTempoOp
    def AtTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SetTempoOp
    def Bpm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetTempoOpStart(builder):
    builder.StartObject(2)

def Start(builder):
    SetTempoOpStart(builder)

def SetTempoOpAddAtTicks(builder, atTicks):
    builder.PrependInt64Slot(0, atTicks, 0)

def AddAtTicks(builder, atTicks):
    SetTempoOpAddAtTicks(builder, atTicks)

def SetTempoOpAddBpm(builder, bpm):
    builder.PrependFloat32Slot(1, bpm, 0.0)

def AddBpm(builder, bpm):
    SetTempoOpAddBpm(builder, bpm)

def SetTempoOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetTempoOpEnd(builder)
