# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetTrackPanOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetTrackPanOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetTrackPanOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetTrackPanOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetTrackPanOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetTrackPanOp
    def Pan(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetTrackPanOpStart(builder):
    builder.StartObject(2)

def Start(builder):
    SetTrackPanOpStart(builder)

def SetTrackPanOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    SetTrackPanOpAddTrackId(builder, trackId)

def SetTrackPanOpAddPan(builder, pan):
    builder.PrependFloat32Slot(1, pan, 0.0)

def AddPan(builder, pan):
    SetTrackPanOpAddPan(builder, pan)

def SetTrackPanOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetTrackPanOpEnd(builder)
