# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetTrackMuteOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetTrackMuteOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetTrackMuteOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetTrackMuteOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetTrackMuteOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetTrackMuteOp
    def Muted(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SetTrackMuteOpStart(builder):
    builder.StartObject(2)

def Start(builder):
    SetTrackMuteOpStart(builder)

def SetTrackMuteOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    SetTrackMuteOpAddTrackId(builder, trackId)

def SetTrackMuteOpAddMuted(builder, muted):
    builder.PrependBoolSlot(1, muted, 0)

def AddMuted(builder, muted):
    SetTrackMuteOpAddMuted(builder, muted)

def SetTrackMuteOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetTrackMuteOpEnd(builder)
