# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetTrackNameOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetTrackNameOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetTrackNameOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetTrackNameOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetTrackNameOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetTrackNameOp
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SetTrackNameOpStart(builder):
    builder.StartObject(2)

def Start(builder):
    SetTrackNameOpStart(builder)

def SetTrackNameOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    SetTrackNameOpAddTrackId(builder, trackId)

def SetTrackNameOpAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    SetTrackNameOpAddName(builder, name)

def SetTrackNameOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetTrackNameOpEnd(builder)
