# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetTrackGainOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetTrackGainOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetTrackGainOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetTrackGainOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetTrackGainOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetTrackGainOp
    def GainLinear(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SetTrackGainOpStart(builder):
    builder.StartObject(2)

def Start(builder):
    SetTrackGainOpStart(builder)

def SetTrackGainOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    SetTrackGainOpAddTrackId(builder, trackId)

def SetTrackGainOpAddGainLinear(builder, gainLinear):
    builder.PrependFloat32Slot(1, gainLinear, 0.0)

def AddGainLinear(builder, gainLinear):
    SetTrackGainOpAddGainLinear(builder, gainLinear)

def SetTrackGainOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetTrackGainOpEnd(builder)
