# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetTrackSoloOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetTrackSoloOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetTrackSoloOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetTrackSoloOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetTrackSoloOp
    def TrackId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SetTrackSoloOp
    def Soloed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def SetTrackSoloOpStart(builder):
    builder.StartObject(2)

def Start(builder):
    SetTrackSoloOpStart(builder)

def SetTrackSoloOpAddTrackId(builder, trackId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(trackId), 0)

def AddTrackId(builder, trackId):
    SetTrackSoloOpAddTrackId(builder, trackId)

def SetTrackSoloOpAddSoloed(builder, soloed):
    builder.PrependBoolSlot(1, soloed, 0)

def AddSoloed(builder, soloed):
    SetTrackSoloOpAddSoloed(builder, soloed)

def SetTrackSoloOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SetTrackSoloOpEnd(builder)
