# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SplitClipOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SplitClipOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSplitClipOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SplitClipOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SplitClipOp
    def ClipId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SplitClipOp
    def AtTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # SplitClipOp
    def NewClipId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def SplitClipOpStart(builder):
    builder.StartObject(3)

def Start(builder):
    SplitClipOpStart(builder)

def SplitClipOpAddClipId(builder, clipId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clipId), 0)

def AddClipId(builder, clipId):
    SplitClipOpAddClipId(builder, clipId)

def SplitClipOpAddAtTicks(builder, atTicks):
    builder.PrependInt64Slot(1, atTicks, 0)

def AddAtTicks(builder, atTicks):
    SplitClipOpAddAtTicks(builder, atTicks)

def SplitClipOpAddNewClipId(builder, newClipId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(newClipId), 0)

def AddNewClipId(builder, newClipId):
    SplitClipOpAddNewClipId(builder, newClipId)

def SplitClipOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return SplitClipOpEnd(builder)
