# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

class TelemetryEvent(object):
    NONE = 0
    ClockSnapshot = 1
    MeterFrame = 2
    SaveResultEvent = 3
    TransportAck = 4
