# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TransportRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TransportRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTransportRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TransportRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TransportRequest
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TransportRequest
    def ProjectId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TransportRequest
    def EngineEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TransportRequest
    def Op(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TransportRequest
    def PositionTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return -1

    # TransportRequest
    def CycleStartTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TransportRequest
    def CycleEndTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TransportRequest
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def TransportRequestStart(builder):
    builder.StartObject(8)

def Start(builder):
    TransportRequestStart(builder)

def TransportRequestAddRequestId(builder, requestId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)

def AddRequestId(builder, requestId):
    TransportRequestAddRequestId(builder, requestId)

def TransportRequestAddProjectId(builder, projectId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(projectId), 0)

def AddProjectId(builder, projectId):
    TransportRequestAddProjectId(builder, projectId)

def TransportRequestAddEngineEpoch(builder, engineEpoch):
    builder.PrependUint64Slot(2, engineEpoch, 0)

def AddEngineEpoch(builder, engineEpoch):
    TransportRequestAddEngineEpoch(builder, engineEpoch)

def TransportRequestAddOp(builder, op):
    builder.PrependInt8Slot(3, op, 0)

def AddOp(builder, op):
    TransportRequestAddOp(builder, op)

def TransportRequestAddPositionTicks(builder, positionTicks):
    builder.PrependInt64Slot(4, positionTicks, -1)

def AddPositionTicks(builder, positionTicks):
    TransportRequestAddPositionTicks(builder, positionTicks)

def TransportRequestAddCycleStartTicks(builder, cycleStartTicks):
    builder.PrependInt64Slot(5, cycleStartTicks, 0)

def AddCycleStartTicks(builder, cycleStartTicks):
    TransportRequestAddCycleStartTicks(builder, cycleStartTicks)

def TransportRequestAddCycleEndTicks(builder, cycleEndTicks):
    builder.PrependInt64Slot(6, cycleEndTicks, 0)

def AddCycleEndTicks(builder, cycleEndTicks):
    TransportRequestAddCycleEndTicks(builder, cycleEndTicks)

def TransportRequestAddValue(builder, value):
    builder.PrependFloat32Slot(7, value, 0.0)

def AddValue(builder, value):
    TransportRequestAddValue(builder, value)

def TransportRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return TransportRequestEnd(builder)
