# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

class TransportOp(object):
    PLAY = 0
    STOP = 1
    SEEK = 2
    PANIC = 3
    SET_CYCLE = 4
    SET_TEMPO_LIVE = 5
