# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TransportAck(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TransportAck()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTransportAck(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TransportAck
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TransportAck
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TransportAck
    def Ok(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # TransportAck
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def TransportAckStart(builder):
    builder.StartObject(3)

def Start(builder):
    TransportAckStart(builder)

def TransportAckAddRequestId(builder, requestId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)

def AddRequestId(builder, requestId):
    TransportAckAddRequestId(builder, requestId)

def TransportAckAddOk(builder, ok):
    builder.PrependBoolSlot(1, ok, 0)

def AddOk(builder, ok):
    TransportAckAddOk(builder, ok)

def TransportAckAddError(builder, error):
    builder.PrependUint16Slot(2, error, 0)

def AddError(builder, error):
    TransportAckAddError(builder, error)

def TransportAckEnd(builder):
    return builder.EndObject()

def End(builder):
    return TransportAckEnd(builder)
