# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TrimClipOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TrimClipOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTrimClipOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TrimClipOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TrimClipOp
    def ClipId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # TrimClipOp
    def StartTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TrimClipOp
    def LengthTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TrimClipOp
    def OffsetTicks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def TrimClipOpStart(builder):
    builder.StartObject(4)

def Start(builder):
    TrimClipOpStart(builder)

def TrimClipOpAddClipId(builder, clipId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clipId), 0)

def AddClipId(builder, clipId):
    TrimClipOpAddClipId(builder, clipId)

def TrimClipOpAddStartTicks(builder, startTicks):
    builder.PrependInt64Slot(1, startTicks, 0)

def AddStartTicks(builder, startTicks):
    TrimClipOpAddStartTicks(builder, startTicks)

def TrimClipOpAddLengthTicks(builder, lengthTicks):
    builder.PrependInt64Slot(2, lengthTicks, 0)

def AddLengthTicks(builder, lengthTicks):
    TrimClipOpAddLengthTicks(builder, lengthTicks)

def TrimClipOpAddOffsetTicks(builder, offsetTicks):
    builder.PrependInt64Slot(3, offsetTicks, 0)

def AddOffsetTicks(builder, offsetTicks):
    TrimClipOpAddOffsetTicks(builder, offsetTicks)

def TrimClipOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return TrimClipOpEnd(builder)
