# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UndoOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UndoOp()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUndoOp(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UndoOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UndoOp
    def TransactionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UndoOpStart(builder):
    builder.StartObject(1)

def Start(builder):
    UndoOpStart(builder)

def UndoOpAddTransactionId(builder, transactionId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(transactionId), 0)

def AddTransactionId(builder, transactionId):
    UndoOpAddTransactionId(builder, transactionId)

def UndoOpEnd(builder):
    return builder.EndObject()

def End(builder):
    return UndoOpEnd(builder)
