# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

class ViewKind(object):
    PROJECT_SUMMARY = 0
    TRACK_LIST = 1
    CLIP_LIST = 2
    NOTE_RANGE = 3
    ASSET_LIST = 4
    PLUGIN_LIST = 5
    RECEIPT_LIST = 6
