# automatically generated by the FlatBuffers compiler, do not modify

# namespace: voidproto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorkerHello(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerHello()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerHello(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorkerHello
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerHello
    def WorkerKind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # WorkerHello
    def WorkerInstanceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorkerHello
    def ProtocolMajor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # WorkerHello
    def ProtocolMinor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # WorkerHello
    def LaunchToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorkerHello
    def EngineEpoch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # WorkerHello
    def Capabilities(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # WorkerHello
    def CapabilitiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WorkerHello
    def CapabilitiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def WorkerHelloStart(builder):
    builder.StartObject(7)

def Start(builder):
    WorkerHelloStart(builder)

def WorkerHelloAddWorkerKind(builder, workerKind):
    builder.PrependInt8Slot(0, workerKind, 0)

def AddWorkerKind(builder, workerKind):
    WorkerHelloAddWorkerKind(builder, workerKind)

def WorkerHelloAddWorkerInstanceId(builder, workerInstanceId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(workerInstanceId), 0)

def AddWorkerInstanceId(builder, workerInstanceId):
    WorkerHelloAddWorkerInstanceId(builder, workerInstanceId)

def WorkerHelloAddProtocolMajor(builder, protocolMajor):
    builder.PrependUint16Slot(2, protocolMajor, 0)

def AddProtocolMajor(builder, protocolMajor):
    WorkerHelloAddProtocolMajor(builder, protocolMajor)

def WorkerHelloAddProtocolMinor(builder, protocolMinor):
    builder.PrependUint16Slot(3, protocolMinor, 0)

def AddProtocolMinor(builder, protocolMinor):
    WorkerHelloAddProtocolMinor(builder, protocolMinor)

def WorkerHelloAddLaunchToken(builder, launchToken):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(launchToken), 0)

def AddLaunchToken(builder, launchToken):
    WorkerHelloAddLaunchToken(builder, launchToken)

def WorkerHelloAddEngineEpoch(builder, engineEpoch):
    builder.PrependUint64Slot(5, engineEpoch, 0)

def AddEngineEpoch(builder, engineEpoch):
    WorkerHelloAddEngineEpoch(builder, engineEpoch)

def WorkerHelloAddCapabilities(builder, capabilities):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(capabilities), 0)

def AddCapabilities(builder, capabilities):
    WorkerHelloAddCapabilities(builder, capabilities)

def WorkerHelloStartCapabilitiesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCapabilitiesVector(builder, numElems):
    return WorkerHelloStartCapabilitiesVector(builder, numElems)

def WorkerHelloEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorkerHelloEnd(builder)
